---
- name: AUTOMATIC BACKUP OF RUNNING-CONFIG
  hosts: CSR1kV
  gather_facts: false
  connection: local
 
  tareas:
   - name: DISPLAYING THE RUNNING-CONFIG
     ios_command:
       a continuación:
         - show running-config  
     register: config
 
   - name: SAVE OUTPUT TO ./backups/
     copy:
       content: "{{ config.stdout[0] }}"
       dest: «backups/show_run_ {{inventory_hostname}} .txt»
