// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.last_seen_buildid", "20200602222727");
user_pref("app.normandy.migrationsApplied", 9);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1782283939);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1779402209);
user_pref("app.update.lastUpdateTime.rs-experiment-loader-timer", 1782283914);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 0);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 0);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.amount_written", 2626);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1779402206);
user_pref("browser.laterrun.bookkeeping.sessionCount", 2);
user_pref("browser.migration.version", 94);
user_pref("browser.newtabpage.activity-stream.impressionId", "{af624a43-09c1-4504-8b65-4d8c7a30bd18}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"pinTab\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1782283927910");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1782285704910");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1782283917597");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1782305517597");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20200602222727");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1782283914");
user_pref("browser.slowStartup.averageTime", 6825);
user_pref("browser.slowStartup.samples", 2);
user_pref("browser.startup.homepage_override.buildID", "20200602222727");
user_pref("browser.startup.homepage_override.mstone", "77.0.1");
user_pref("browser.startup.lastColdStartupCheck", 1782283912);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"toolbar-menubar\",\"TabsToolbar\",\"PersonalToolbar\"],\"currentVersion\":16,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1779402210036");
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "77.0.1");
user_pref("distribution.iniFile.exists.value", true);
user_pref("doh-rollout.balrog-migration-done", true);
user_pref("dom.push.userAgentID", "89380f17fbf24f4a9b3454f40117f028");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 32);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppBuildId", "20200602222727");
user_pref("extensions.lastAppVersion", "77.0.1");
user_pref("extensions.lastPlatformVersion", "77.0.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.doh-rollout@mozilla.org", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"doh-rollout@mozilla.org\":\"e50853c2-4dca-48d4-a683-83e1fbd5893c\",\"formautofill@mozilla.org\":\"7dd11340-96fa-46e3-a545-dff89a8d47de\",\"screenshots@mozilla.org\":\"86a1ec7d-9d8b-4c18-a756-b4d6c3c59567\",\"webcompat-reporter@mozilla.org\":\"866d4d27-9e19-454d-99fb-e5d3099d7f48\",\"webcompat@mozilla.org\":\"79c2eff9-6328-4fbf-8d0f-32eb824ead53\",\"default-theme@mozilla.org\":\"bf3e0afc-2450-4fad-ac5d-75e2b80341ea\",\"google@search.mozilla.org\":\"01ba110c-5f31-40e8-b7e4-959130b490d5\",\"amazondotcom@search.mozilla.org\":\"0905e763-fd66-4a62-93cd-a258743b9e54\",\"bing@search.mozilla.org\":\"ba67794f-9fee-4c58-b737-ca5e9e843189\",\"ddg@search.mozilla.org\":\"16ef35ef-e74c-4a84-9651-30c3e3ee3ff8\",\"ebay@search.mozilla.org\":\"9e8bfa4f-60f2-493f-b522-ce01dc920aed\",\"twitter@search.mozilla.org\":\"6e1a265a-21c1-46a4-bad3-319e2b583e57\",\"wikipedia@search.mozilla.org\":\"1182a6ca-7fe7-43be-9f3f-a0d3ac9f77dc\"}");
user_pref("gfx.blacklist.layers.opengl", 4);
user_pref("gfx.blacklist.layers.opengl.failureid", "FEATURE_FAILURE_SOFTWARE_GL");
user_pref("media.gmp.storage.version.observed", 1);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "63437f00-87a5-4b55-8327-8765b0cc1eef");
user_pref("security.sandbox.plugin.tempDirSuffix", "65477613-9278-4109-b6ec-e673e6e11299");
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.startup.last_success", 1782283905);
user_pref("toolkit.telemetry.cachedClientID", "db6b06bf-d98a-4091-b712-5e9981f30610");
user_pref("toolkit.telemetry.previousBuildID", "20200602222727");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
